# Generated by Django 4.2 on 2023-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
