# Generated by Django 4.1.7 on 2023-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('password', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
